channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - qpdf=10.6.3
  - ghostscript=9.54.0
  - tesseract=5.2.0
  - img2pdf=0.4.4
  - ocrmypdf=14.0.1
  - pip=22.1.2
  - pip:
    - rpaframework==19.4.1
